# Generated by Django 4.2 on 2025-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_director_movie_genre_movie_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.CharField(default='Unknown author', max_length=100),
        ),
    ]
